#!/bin/bash

R="http://shinysocks.net/radio"
S="$R/elapsed"

while true;
do
    # mpv --quiet --no-video --start="+$(curl $S)" "$R"
    curl -s "$R" | ffplay -autoexit -nodisp -hide_banner -loglevel error -ss $(curl -s $S)s -
done
